groups:
  - name: application_alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: http_error_rate > 5
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value }}%, which is above the 5% threshold"

      # Slow response time
      - alert: SlowResponseTime
        expr: http_response_time_milliseconds{quantile="0.95"} > 2000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Slow API response time"
          description: "95th percentile response time is {{ $value }}ms"

      # High memory usage
      - alert: HighMemoryUsage
        expr: (process_memory_bytes{type="heapUsed"} / process_memory_bytes{type="heapTotal"}) * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage"
          description: "Memory usage is {{ $value }}%"

      # Application down
      - alert: ApplicationDown
        expr: up{job="cryptons-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Application is down"
          description: "The application has been down for more than 1 minute"

      # Low cache hit rate
      - alert: LowCacheHitRate
        expr: cache_hit_rate < 50
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Low cache hit rate"
          description: "Cache hit rate is {{ $value }}%, consider reviewing cache strategy"

  - name: database_alerts
    interval: 30s
    rules:
      # Database connection issues
      - alert: DatabaseConnectionFailed
        expr: up{job="mongodb"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection failed"
          description: "Cannot connect to MongoDB"

      # Slow database queries
      - alert: SlowDatabaseQueries
        expr: db_queries_total > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High number of database queries"
          description: "Database query count is {{ $value }}"

  - name: system_alerts
    interval: 30s
    rules:
      # High CPU usage
      - alert: HighCPUUsage
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for {{ $labels.instance }}"

      # Disk space low
      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 20
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space"
          description: "Disk space is below 20% on {{ $labels.instance }}"

      # Container restarting
      - alert: ContainerRestarting
        expr: rate(container_last_seen{name=~"cryptons.*"}[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Container is restarting"
          description: "Container {{ $labels.name }} is restarting frequently"
