version: '3.8'

services:
  # Elasticsearch - Log storage and search
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.0
    container_name: cryptons-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - cryptons-logging

  # Logstash - Log processing and enrichment
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.0
    container_name: cryptons-logstash
    restart: unless-stopped
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      - "LS_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ../monitoring/logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ../monitoring/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on:
      - elasticsearch
    networks:
      - cryptons-logging

  # Kibana - Log visualization and analysis
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.0
    container_name: cryptons-kibana
    restart: unless-stopped
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    volumes:
      - kibana_data:/usr/share/kibana/data
    depends_on:
      - elasticsearch
    networks:
      - cryptons-logging

  # Filebeat - Log shipper (optional, for file-based logs)
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.10.0
    container_name: cryptons-filebeat
    restart: unless-stopped
    user: root
    volumes:
      - ../monitoring/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../logs:/logs:ro
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch
      - logstash
    networks:
      - cryptons-logging

networks:
  cryptons-logging:
    driver: bridge

volumes:
  elasticsearch_data:
  kibana_data:
