apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: cstore
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /tmp/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;

        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        client_max_body_size 20M;

        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_types text/plain text/css text/xml text/javascript 
                   application/json application/javascript application/xml+rss 
                   application/rss+xml font/truetype font/opentype 
                   application/vnd.ms-fontobject image/svg+xml;

        # CDN and caching headers
        map $sent_http_content_type $expires {
            default                    off;
            text/html                  epoch;
            text/css                   max;
            application/javascript     max;
            application/json           epoch;
            ~image/                    max;
            ~font/                     max;
            ~video/                    max;
        }

        server {
            listen 8080;
            server_name _;
            
            expires $expires;

            # Security headers
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            add_header Referrer-Policy "no-referrer-when-downgrade" always;

            # CDN-friendly cache headers for static assets
            location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
                root /usr/share/nginx/html;
                expires 1y;
                add_header Cache-Control "public, immutable";
                add_header X-Content-Type-Options "nosniff" always;
                add_header Access-Control-Allow-Origin "*";
                try_files $uri =404;
            }

            # Static HTML files
            location / {
                root /usr/share/nginx/html;
                index index.html;
                expires epoch;
                add_header Cache-Control "no-cache, must-revalidate";
                try_files $uri $uri/ /index.html;
            }

            # Health check endpoint
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            # Metrics endpoint for monitoring
            location /nginx_status {
                stub_status on;
                access_log off;
                allow 10.0.0.0/8;
                deny all;
            }
        }
    }
